-- AlterTable
ALTER TABLE "Exercise" ALTER COLUMN "video_url" DROP NOT NULL,
ALTER COLUMN "primary_muscle" DROP DEFAULT,
ALTER COLUMN "equipment" DROP DEFAULT,
ALTER COLUMN "difficulty" DROP DEFAULT,
ALTER COLUMN "exercise_type" DROP DEFAULT,
ALTER COLUMN "movement_pattern" DROP DEFAULT,
ALTER COLUMN "workout_location" DROP DEFAULT,
ALTER COLUMN "media_type" DROP DEFAULT,
ALTER COLUMN "priority" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
