/*
  Warnings:

  - The values [ST_INJURIES,REALISTIC_TRAINING_DAYS,DIET_OR_NUTRITION_PLAN,ACTIVITY_LEVEL,FITNESS_PREFERENCES,TYPICAL_EATING_DAY,TRAINING_TIME_COMMITMENT,MOTIVATION,MILESTONES_OR_DEADLINES,CURRENT_WEIGHT,CURRENT_HEIGHT,PRIMARY_FITNESS_GOALS] on the enum `IntakeQuestionKey` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "IntakeQuestionKey_new" AS ENUM ('AGE', 'GENDER', 'HEIGHT_CM', 'WEIGHT_KG', 'PRIMARY_FITNESS_GOAL', 'GOAL_IMPORTANCE', 'TARGET_TIMELINE', 'FITNESS_LEVEL', 'PREVIOUS_PROGRAM_EXPERIENCE', 'PREVIOUS_TRAINER_EXPERIENCE', 'MEDICAL_CONDITIONS', 'CURRENT_MEDICATIONS', 'PAST_INJURIES', 'DOCTOR_EXERCISE_RESTRICTION', 'EXPECTED_CHALLENGES', 'SLEEP_HOURS', 'OCCUPATION', 'STRESS_LEVEL', 'SMOKE_DRINK_ALCOHOL', 'COMMITMENT_DAYS_PER_WEEK', 'CURRENTLY_EXERCISING', 'TRAINING_DAYS_PER_WEEK', 'CURRENT_EXERCISE_TYPE', 'SESSION_DURATION_MINUTES', 'DAILY_DIET_DESCRIPTION', 'MEALS_PER_DAY', 'WATER_INTAKE_LITERS', 'FOOD_ALLERGIES_RESTRICTIONS', 'SPECIFIC_DIET', 'PREFERRED_WORKOUT_LOCATION', 'PREFERRED_WORKOUT_DURATION', 'PREFERRED_TRAINING_TYPE');
ALTER TABLE "IntakeAnswer" ALTER COLUMN "question" TYPE "IntakeQuestionKey_new" USING ("question"::text::"IntakeQuestionKey_new");
ALTER TYPE "IntakeQuestionKey" RENAME TO "IntakeQuestionKey_old";
ALTER TYPE "IntakeQuestionKey_new" RENAME TO "IntakeQuestionKey";
DROP TYPE "public"."IntakeQuestionKey_old";
COMMIT;
