/*
  Warnings:

  - The values [AGE,GENDER,TARGET_TIMELINE,PREVIOUS_TRAINER_EXPERIENCE,SPECIFIC_DIET,PREFERRED_WORKOUT_DURATION,PREFERRED_TRAINING_TYPE] on the enum `IntakeQuestionKey` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "IntakeQuestionKey_new" AS ENUM ('SLEEP_HOURS', 'OCCUPATION', 'STRESS_LEVEL', 'SMOKE_DRINK_ALCOHOL', 'COMMITMENT_DAYS_PER_WEEK', 'PREFERRED_WORKOUT_LOCATION', 'FITNESS_LEVEL', 'DAILY_DIET_DESCRIPTION', 'MEALS_PER_DAY', 'WATER_INTAKE_LITERS', 'CURRENT_EXERCISE_TYPE', 'FOOD_ALLERGIES_RESTRICTIONS', 'PAST_INJURIES', 'DOCTOR_EXERCISE_RESTRICTION', 'CURRENTLY_EXERCISING', 'TRAINING_DAYS_PER_WEEK', 'SESSION_DURATION_MINUTES', 'HEIGHT_CM', 'WEIGHT_KG', 'PRIMARY_FITNESS_GOAL', 'PREVIOUS_PROGRAM_EXPERIENCE', 'GOAL_IMPORTANCE', 'MEDICAL_CONDITIONS', 'CURRENT_MEDICATIONS', 'EXPECTED_CHALLENGES');
ALTER TABLE "IntakeAnswer" ALTER COLUMN "question" TYPE "IntakeQuestionKey_new" USING ("question"::text::"IntakeQuestionKey_new");
ALTER TYPE "IntakeQuestionKey" RENAME TO "IntakeQuestionKey_old";
ALTER TYPE "IntakeQuestionKey_new" RENAME TO "IntakeQuestionKey";
DROP TYPE "public"."IntakeQuestionKey_old";
COMMIT;
